services:
  tabletap-nextjs:
    build: 
      context: .
      args:
        - BACKEND_URL
        - NEXTAUTH_URL
        - NEXTAUTH_SECRET
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - caddy_network

networks:
  caddy_network:
    external: true
    name: caddy_network
